apiVersion: v1
kind: Service
metadata:
  name: "mysql-${service_id}"
  namespace: "${service_namespace}"
spec:
  selector:
    app: "mysql-${service_id}"
  type: "${service_endpoint_type}"
  sessionAffinity: None
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800
  ports:
  - name: mysql
    protocol: TCP
    port: 3306
    targetPort: 3306