apiVersion: v1
kind: Service
metadata:
  name: "couchdb-${service_id}"
  namespace: "${service_namespace}"
spec:
  selector:
    app: "couchdb-${service_id}"
  type: "${service_endpoint_type}"
  sessionAffinity: None
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800
  ports:
  - name: http
    protocol: TCP
    port: 5984
    targetPort: 5984