apiVersion: v1
kind: Service
metadata:
  name: "rabbitmq-${service_id}"
  namespace: "${service_namespace}"
spec:
  selector:
    app: "rabbitmq-${service_id}"
  type: "${service_endpoint_type}"
  sessionAffinity: None
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800
  ports:
  - name: api
    protocol: TCP
    port: 5672
    targetPort: 5672
  - name: console
    protocol: TCP
    port: 15672
    targetPort: 15672
