apiVersion: v1
kind: Service
metadata:
  name: "minio-${service_id}"
  namespace: "${service_namespace}"
spec:
  selector:
    app: "minio-${service_id}"
  type: "${service_endpoint_type}"
  sessionAffinity: None
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800
  ports:
  - name: api
    protocol: TCP
    port: 9000
    targetPort: 9000
  - name: console
    protocol: TCP
    port: 9001
    targetPort: 9001